### ISSUE TITLE
Switch desktop animations

### ISSUE THREAD

**Issue by theCoffeeProject** [MScholtes/PSVirtualDesktop#12]
In Windows there is an animation for switching to the left and right desktop if you use the keyboard shortcut or touchpad gesture. At the moment the module doesn't make any difference between switching to one or another desktop.

Is it possible to switch to the left and right desktop in the same animated way Windows does it when pressing the shortcut? Does the API provide any way to achieve that result programatically?

**Comment by MScholtes** [comment]
Hello theCoffeeProject,

the main problem with this question is that the API for controlling virtual desktops is not documented. I have no idea how to realise this.

So far I haven't looked into it either, because I assume that if there is an animation, the commandlets would have to wait until the animation is done. This contradicts my actual concepts.

But if you have any hints on how to programme this (without investing weeks of work), I would be pleased to look into it.

Greetings

Markus

**Comment by theCoffeeProject** [comment]
Hello Markus,

thanks for your reply.

I wish I could help but unfortunately, I'm not really experienced in programming for Windows. I know that the API is not documented, but how can you approah such a problem? How can you find out about the classes and methods to use if there is no information about them?

> I assume [...] the commandlets would have to wait until the animation is done. This contradicts my actual concepts.

If this is the case, would it be possible to run that part of the code in the background, in a new PowerShell job? If I'm not mistaken, the script wouldn't have to wait for the new job (including the animation) to finish before continuing with its instructions. But I don't know if there are more drawbacks than that? Switching desktops doesn't give any return value that you have to wait for, up to now.

However, this doesn't help if there is no approach to the problem in the first place. Still, thanks for your effort.

Greetings,
the CoffeeProject

**Comment by MScholtes** [comment]
Closed since no response for about 3 weeks
