### ISSUE TITLE
API to rename the virtual desktop or creating a named desktop

### ISSUE THREAD

**Issue by sathish25071992** [MScholtes/PSVirtualDesktop#2]
Hi,
Can we create a named virtual desktop using this module or is it possible to rename already existing desktop?

**Comment by MScholtes** [comment]
Hello Sathish.

Microsoft did not document the API for (re)naming desktops. So to implement those functions there is the need to reverse engineer the appropriate DLLs or COM calls.

Because of the Corona virus outbreak and the need to care for my children who currently have no school I have no free time to deal with these time-consuming issues. 

However, if anyone finds out anything about the API, I would be very grateful for any information.

Greetings

Markus

**Comment by sathish25071992** [comment]
😅. I can understand that. Let me check what I can find on my freetime. stay safe.
