### ISSUE TITLE
problem when try to move virtualbox machine

### ISSUE THREAD

**Issue by Ludo-code** [MScholtes/PSVirtualDesktop#22]
Hello, 

I have no problem to move notepad to my 1 virtual screen (see Bellow) 

```powershell
Move-Window -Desktop (Desktop 1) -Hwnd ((Get-Process "notepad")[0].MainWindowHandle)
```

but when trying with the process of vbox with the following command :

```powershell
Move-Window -Desktop (Desktop 1) -Hwnd ((Get-Process "VirtualBoxVM")[0].MainWindowHandle)
```

but i have the following error : 

```powershell
PS C:\Users\lasag> Move-Window -Desktop (Desktop 1) -Hwnd ((Get-Process "VirtualBoxVM")[0].MainWindowHandle)
MethodInvocationException: C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.5.1\VirtualDesktop.ps1:2305:3
Line |
2305 |          $Desktop.MoveWindow($Hwnd)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "MoveWindow" with "1" argument(s): "Value cannot be null."

IsVisible Left                   Right
--------- ----                   -----
    False VirtualDesktop.Desktop
   
```

**Comment by MScholtes** [comment]
Hello @Ludo-code,

the reason for the error is that the expression **(Get-Process "VirtualBoxVM")[0].MainWindowHandle** returns **0** or **$NULL**. This is because the selected process does not have a main window (and therefore no window at all).

I do not use **VirtualBox** so I cannot say anything to the process and window management of the tool, but I think you have to search for the process that owns the window you want to move to another desktop and use its window handle.

Greetings

Markus

**Comment by Ludo-code** [comment]
I have modified to get the process number because of multiple process with the same name.... it's working fine but if i close and re open the machine the process is changing (logic) have you an idea to bypass this ?

**Comment by MScholtes** [comment]
Hello @Ludo-code,

for situations like this I delivered the commandlet **Find-WindowHandle**.
With
```powershell
Find-WindowHandle '*'
```
you get a list of all current window titles. Please look for the title of the window you want to move.

Then you can move this window with a command like
```powershell
Move-Window -Desktop (Desktop 1) -Hwnd (Find-WindowHandle "THE TITLE OF THE DESIRED WINDOW")
```

I hope this works with **VirtualBox**.

Greetings

Markus

**Comment by MScholtes** [comment]
No response, assuming it is solved
