### ISSUE TITLE
Windows 11 Insiders fails to initialize

### ISSUE THREAD

**Issue by t1m0thyj** [MScholtes/PSVirtualDesktop#23]
Same issue as the one reported [here](https://github.com/MScholtes/PSVirtualDesktop/issues/14#issuecomment-1221552707) (TypeInitializationException)

To fix it, I believe the changes from https://github.com/MScholtes/VirtualDesktop/pull/48 would need to be applied to this repo.

**Comment by MScholtes** [comment]
Hello @t1m0thyj,

I always keep my two virtual desktop tools in sync, so the change you mention is already built in.

Microsoft changed the COM API for virtual desktops with Windows Insider 25290 again, this breaks both of the tools.

For me, the effort to find out the changes in the Insider version is too high, since a new change can come every day that destroys my efforts (I don't have an Insider version either). If someone reports the changes to me, I will gladly incorporate them.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @t1m0thyj,

thank you very much for your work, I integrated this in the new version of PSVirtualDesktop.

In most of the cases it is too painstaking to merge a pull request because of the companion repositories https://github.com/MScholtes/TechNet-Gallery and https://github.com/MScholtes/VirtualDesktop. My root repository is at home...

Greetings

Markus

**Comment by t1m0thyj** [comment]
No worries, thanks for releasing the update. Confirmed that it works for me 👍
