### ISSUE TITLE
How hard would it be to add shortcuts?

### ISSUE THREAD

**Issue by shellwhale** [MScholtes/PSVirtualDesktop#26]
I'd like to be able to switch desktops by using shortcuts.
By default, we can use CTRL + WINDOWS + Right/Left in order to switch between desktops but I'd like to also be able to use numbers.

CTRL + WINDOWS + <NUMBER> would go to desktop <NUMBER>

Any idea on how I could implement this? Would it be fast to run your PowerShell commands after pressing a key?

**Comment by MScholtes** [comment]
Hello @shellwhale,

I would advice you to use a shortcut tool like **Autohotkey** to set the key combination. Using **PSVirtualDesktop** to switch the desktops would be too slow since it's a **Powershell** script. You might use the companion tool **VirtualDesktop** (https://github.com/MScholtes/VirtualDesktop) instead.

Or the best would be using something like the answer solution here: https://superuser.com/questions/1685845/moving-current-window-to-another-desktop-in-windows-11-using-shortcut-keys 

Greetings

Markus

**Comment by shellwhale** [comment]
I managed to simply run .bat files that call **VirtualDesktop.exe** using Corsair's Icue, as I explained [here](https://github.com/MScholtes/VirtualDesktop/issues/23#issuecomment-1468394097l) 😀

Worked perfectly on my old system but not on my new system, can't figure out why! Otherwise, your tool is really great, and perfect for my use case.

**Comment by MScholtes** [comment]
Workaround exists
