### ISSUE TITLE
When switching desktops there are no active windows.

### ISSUE THREAD

**Issue by tgienger** [MScholtes/PSVirtualDesktop#39]
When switching desktops all windows are deselected. It would be best to be able to switch to a desktop and have the topmost application already selected. Right now if I switch desktops I have to still use my mouse to select a window or alt-tab.

**Comment by MScholtes** [comment]
Hello @tgienger,

I think I have no satisfying solution for you. Windows does not maintain one active window per virtual desktop, but only one active wIndow per login. So if you switch to another desktop "low level" with **PSVirtualDesktop**, a window on the last active virtual desktop is still the active window and no window on the now current displayed virtual desktop!

The best way to get around this is to activate the "desktop window" directly after switching and then tell the "desktop window" to give away activation, That's what **PSVirtualDesktop** does, and most of the times it works (other tools use the task bar what works with very similiar success). But it does not succeed in all cases because it depends on the willingness of the window that gets the focus.

There was a long discussion about this in an issue in the partner project **VirtualDesktop**: https://github.com/MScholtes/VirtualDesktop/issues/57

Greetings

Markus

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
