### ISSUE TITLE
Feedback and Request

### ISSUE THREAD

**Issue by sirouk** [MScholtes/PSVirtualDesktop#45]
This is absolutely wonderful and going to save me a lot of time 😁 

Would there be a way to move a window to a particular screen within the Virtual Desktop?

**Comment by MScholtes** [comment]
Hello @sirouk,

thank you for your feedback.

When I understand your question right you are looking for a way to move a window to maybe a second monitor? No, this is not implemented in PSVirtualDesktop, since it has nothing to do with virtual desktops.
A shot internet search shwoed that it would not bo easy to implement.

Greetings

Markus
